version: '2'
services:
  ejob-o-mat:
    build: .
    ports:
      - '80:40000'
      - '127.0.0.1:50000:50000'
    restart: always
    environment:
      dbHost: mongo
      dbPassword: USER_PASS
      dbUser: ejob-o-mat
      projectName: ejob-o-mat
      SITE_VERIFICATION_TOKEN: 'SITE_VERIFICATION_TOKEN'
    depends_on:
      - mongo
  mongo:
    build: 'https://github.com/SommerEngineering/mongodb.git'
    volumes:
      - 'mongodb:/data/db'
    restart: always
    environment:
      dbHost: some-mongo
      rootPwd: ROOT_PASS
      dataPwd: USER_PASS
      dataUser: ejob-o-mat
      dataName: ejob-o-mat
volumes:
    mongodb: {}